### ISSUE TITLE
Granular metrics for analytics/table

### ISSUE THREAD

**Issue by santanusinha** [Flipkart/foxtrot#74]
Foxtrot needs to provide granular metrics at table level. This includes indexing, get and analysis times. The metrics need to pass through standard flows and be available through the metrics servlet and JMX etc.

**Comment by r0goyal** [comment]
@santanusinha Providing metrics at table level in actions is not generically possible since table is not part of ActionRequest class and instead is part of individual implementations of this class. 

One way I could think of is create an abstract method getMetricKey in Action class and then each implementation defines its own metricKey (Which should have small cardinality since each new value will result in creation of new JMX metric key

**Comment by santanusinha** [comment]
Closed by #133
